- name: Start-Enable Redis instance
  tags:
    - Start-Enable-Redis-instance
  systemd:
    name: redis-server-{{ item }}
    state: started
    enabled: yes
  loop: "{{ range(1, redis_instances_per_host + 1) | list }}"

- name: Restart Redis Instance
  tags:
    - Restart-Redis-Instance
  systemd:
    name: redis-server-{{ item }}
    state: restarted
  loop: "{{ range(1, redis_instances_per_host + 1) | list }}"


- name: Reload systemd
  tags:
    - Reload-systemd
  systemd:
    daemon_reload: yes

